.benchmarks:
- .benchmarks/**
.buildkite:
- .buildkite/**
.pytest_cache:
- .pytest_cache/**
.venv:
- .venv/**
big5:
- big5/**
cohere_vector:
- cohere_vector/**
dense_vector:
- dense_vector/**
elastic:
- elastic/**
elser-ingest-speedtest:
- elser-ingest-speedtest/**
eql:
- eql/**
esql:
- esql/**
full_ci:
- .github/**
geonames:
- geonames/**
geopoint:
- geopoint/**
geopointshape:
- geopointshape/**
geoshape:
- geoshape/**
github_archive:
- github_archive/**
http_logs:
- http_logs/**
it_serverless:
- it_serverless/**
joins:
- joins/**
k8s_metrics:
- k8s_metrics/**
metricbeat:
- metricbeat/**
msmarco-passage-ranking:
- msmarco-passage-ranking/**
msmarco-v2-vector:
- msmarco-v2-vector/**
nested:
- nested/**
noaa:
- noaa/**
nyc_taxis:
- nyc_taxis/**
openai_vector:
- openai_vector/**
percolator:
- percolator/**
pmc:
- pmc/**
random_vector:
- random_vector/**
search:
- search/**
so:
- so/**
so_vector:
- so_vector/**
sql:
- sql/**
tsdb:
- tsdb/**
tsdb_k8s_queries:
- tsdb_k8s_queries/**
wikipedia:
- wikipedia/**
