# Declare a Backstage Component that represents rally-tracks
---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rally-tracks
  description: This repository contains the default track specifications for the Elasticsearch benchmarking tool Rally.
  annotations:
    backstage.io/source-location: url:https://github.com/elastic/rally-tracks
    github.com/project-slug: elastic/rally-tracks
    github.com/team-slug: elastic/es-perf
    buildkite.com/project-slug: elastic/rally-tracks
  tags:
    - elasticsearch
    - benchmark
    - python
    - performance
spec:
  type: application
  owner: group:es-perf
  lifecycle: production
  dependsOn: 
    - "resource:rally-tracks-it"

# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rally-tracks-it
  description: Run tests
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/rally-tracks-it

spec:
  type: buildkite-pipeline
  owner: group:es-perf
  system: buildkite

  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: Rally Tracks - IT
    spec:
      pipeline_file: .buildkite/it/pipeline.yml
      repository: elastic/rally-tracks
      teams:
        es-perf: {}
        everyone:
          access_level: READ_ONLY
