# Licensed to Elasticsearch B.V. under one or more contributor
# license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright
# ownership. Elasticsearch B.V. licenses this file to you under
# the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# 	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

import pytest

class TestTrackRepository:
    skip_tracks = ["elastic/logs", "elastic/security", "sql"]
    disable_assertions = {"http_logs": ["append-no-conflicts", "runtime-fields"]}

    def test_autogenerated(self, es_cluster, rally, track, challenge, rally_options):
        if track not in self.skip_tracks:
            if challenge in self.disable_assertions.get(track, []):
                rally_options.update({"enable_assertions": False})
            ret = rally.race(track=track, challenge=challenge, **rally_options)
            assert ret == 0
        else:
            pytest.skip(msg=f"{track}-{challenge} included in skip list")
