name: Backport reminder

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 06:00 UTC
  workflow_dispatch:
    inputs:
      lookback_days:
        description: 'How many days back to search merged PRs'
        required: false
        default: '7'
      pending_label_age_days:
        description: 'Minimum age in days before reminding'
        required: false
        default: '7'

jobs:
  reminder:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run reminder
        env:
          BACKPORT_TOKEN: ${{ secrets.BACKPORT_TOKEN }}
          LOOKBACK_DAYS: ${{ github.event.inputs.lookback_days || '90' }} # We check PRs LOOKBACK_DAYS old
          PENDING_LABEL_AGE_DAYS: ${{ github.event.inputs.pending_label_age_days || '7' }} # We only remind if the pending label is at least PENDING_LABEL_AGE_DAYS old
        run: python .github/scripts/backport-reminder.py