name: Automatic backport action

on:
  pull_request_target:
    branches: ['master']
    types: ["labeled", "closed"]

jobs:
  backport:
    name: Backport PR
    runs-on: ubuntu-latest
    if: |
        github.event.pull_request.merged == true
        && !contains(github.event.pull_request.labels.*.name, 'backport')
    steps:
      - name: Backport Action
        uses: sorenlouv/backport-github-action@ad888e978060bc1b2798690dd9d03c4036560947  # v9.5.1
        continue-on-error: true
        with:
          github_token: ${{ secrets.BACKPORT_TOKEN }}

      - name: Info log
        if: ${{ success() }}
        run: cat ~/.backport/backport.info.log
        
      - name: Debug log
        if: ${{ failure() }}
        run: cat ~/.backport/backport.debug.log 
